// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brfijyvrbnhvtzarcjaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZmlqeXZyYm5odnR6YXJjamFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDA0MTAsImV4cCI6MjA2MzAxNjQxMH0.7f8RhcZs_cKYQGB_MbJRE1hTYvfrDVQ_gTduZQRQGMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);